name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    # This is needed by puppeteer
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libgbm-dev

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'

    - uses: actions/checkout@v3
      with:
        repository: gauntface/hugo-base-theme-test
    - uses: actions/checkout@v3
      with:
        path: example-site/themes/base-theme/

    - name: Install
      run: |
        npm install
        npm install stylelint-config-standard

    - name: Test
      run: npm run test

    - name: Lint
      run: |
        cd example-site/themes/base-theme/
        npx stylelint '**/*.css'